run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/stalerok/anime_site
  cyclop:
    max-complexity: 30
  gomnd:
    settings:
      mnd:
       ignored-functions: strconv.*
  wrapcheck:
    ignoreSigs:
      - web.Respond
      - web.NewError
      - fmt.Errorf
  dupl:
    threshold: 200

linters:
  enable-all: true
  disable:
    - gci
    - testpackage
    - golint
    - tagliatelle
    - paralleltest
    - maligned
    - scopelint
    - interfacer
    - forcetypeassert
    - exhaustivestruct
    - forbidigo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
